### ISSUE TITLE
crashes immediately on Android

### ISSUE THREAD

**Issue by steveliles** [nitrique/react-native-helpscout-beacon#1]
I get a "Your app crashed" in the log, followed by:

java.lang.LinkageError: Method void org.koin.android.logger.AndroidLogger.log(org.koin.core.logger.Level, java.lang.String) overrides final method in class Lorg/koin/core/logger/Logger; (declaration of 'org.koin.android.logger.AndroidLogger'

**Comment by nitrique** [comment]
Hey,
merged to version 0.6.0, deployed on NPM :)
